<link rel="stylesheet" type="text/css" href="{{asset('assets/css/bootstrap.min.css')}}" media="all" />
<link rel="stylesheet" type="text/css" href="{{asset('assets/css/font-awesome.min.css')}}" media="all" />
<link rel="stylesheet" type="text/css" href="{{asset('assets/css/bootstrap-grid.min.css')}}" media="all" />
<link rel="stylesheet" type="text/css" href="{{asset('assets/css/bootstrap-reboot.min.css')}}" media="all" />
<link rel="stylesheet" type="text/css" href="{{asset('assets/css/font-techmarket.css')}}" media="all" />
<link rel="stylesheet" type="text/css" href="{{asset('assets/css/slick.css')}}" media="all" />
<link rel="stylesheet" type="text/css" href="{{asset('assets/css/techmarket-font-awesome.css')}}" media="all" />
<link rel="stylesheet" type="text/css" href="{{asset('assets/css/slick-style.css')}}" media="all" />
<link rel="stylesheet" type="text/css" href="{{asset('assets/css/animate.min.css')}}" media="all" />
<link rel="stylesheet" type="text/css" href="{{asset('assets/css/style.css')}}" media="all" />
<link rel="stylesheet" type="text/css" href="{{asset('assets/css/custom.css')}}" media="all" />
<link rel="stylesheet" type="text/css" href="{{asset('assets/css/colors/red.css')}}" media="all" />